from artificial_detection.arguments.arguments import form_args
from artificial_detection.arguments.proxy_arguments import form_proxy_args
from artificial_detection.arguments.supervised_arguments import form_supervised_args
